// Mocks generated by Mockito 5.4.6 from annotations
// in cars_app/test/features/push_notification/presentation/cubit/firebase_push_notification_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cars_app/core/failure.dart' as _i6;
import 'package:cars_app/features/push_notification/domain/respositories/push_notification_repository.dart'
    as _i2;
import 'package:cars_app/features/push_notification/domain/usecases/get_fcm_token_usecase.dart'
    as _i4;
import 'package:cars_app/features/push_notification/domain/usecases/push_notification_permission_usecase.dart'
    as _i7;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePushNotificationRepository_0 extends _i1.SmartFake
    implements _i2.PushNotificationRepository {
  _FakePushNotificationRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetFcmTokenUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFcmTokenUsecase extends _i1.Mock
    implements _i4.GetFcmTokenUsecase {
  MockGetFcmTokenUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PushNotificationRepository get pushNotificationRepository =>
      (super.noSuchMethod(
            Invocation.getter(#pushNotificationRepository),
            returnValue: _FakePushNotificationRepository_0(
              this,
              Invocation.getter(#pushNotificationRepository),
            ),
          )
          as _i2.PushNotificationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [PushNotificationPermissionUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPushNotificationPermissionUsecase extends _i1.Mock
    implements _i7.PushNotificationPermissionUsecase {
  MockPushNotificationPermissionUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PushNotificationRepository get pushNotificationRepository =>
      (super.noSuchMethod(
            Invocation.getter(#pushNotificationRepository),
            returnValue: _FakePushNotificationRepository_0(
              this,
              Invocation.getter(#pushNotificationRepository),
            ),
          )
          as _i2.PushNotificationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
              _FakeEither_1<_i6.Failure, bool>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}
