name: cars_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dartz: ^0.10.1
  mockito: ^5.5.0
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  injectable: ^2.5.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  injectable_generator: ^2.8.1

flutter:
  uses-material-design: true
